### ISSUE TITLE
FlowViz Efficiency potentially duplicating day count between old and columns

### ISSUE THREAD

**Issue by jenniferrosemitchell21** [nbrown02/FlowViz#115] opened 2024-01-09 10:56 UTC
**Describe the bug**
Hi Nick, 
I noticed 2 columns showing the same number of calendar days within the FlowViz Efficiency Time in Column Bar Chart. Upon drilling down into the data it appears that the time in column is duplicated. Note that In SA Design was the old name of the column, unfortunately I cannot remember precisely when I changed it. 
Would it be safe then to simply ignore any data in 'old columns', knowing that it is simply a duplication ? Is there anyway to remove the 'old columns' from the data to avoid confusion?

![image](https://github.com/nbrown02/FlowViz/assets/134519976/3d2b99e9-79c6-425b-9801-473b55a64b90)

![image](https://github.com/nbrown02/FlowViz/assets/134519976/d7776a1c-4371-4b3b-a52d-2cca59777b86)

![image](https://github.com/nbrown02/FlowViz/assets/134519976/dc87f862-3167-414c-8de0-f4a74e61ac50)

**Comment by nbrown02** [comment] 2024-01-09 11:07
If there is data for that column name there must be a board somewhere that
has/had that value, it might be a case of area paths spanning multiple
boards but it's hard for me to replicate that setup with the projects I
have :/

Assuming that you are filtering by team in the first instance?

**Comment by nbrown02** [comment] 2024-01-11 08:49
Closing as not a bug, template is just visualizing information that exists in the dataset

**Closed by nbrown02** 2024-01-11 08:49 UTC
Labels: wontfix

**Comment by jenniferrosemitchell21** [comment] 2024-01-11 09:23
Hi Nick, yes filtering by Team. The board has been renamed so I do expect to still see the 2 columns. I would expect to see different dates though. i.e. a ticket is in the column for 10 days and I changed the column name halfway through. In this case I I would expect to see 5 days count in the old column name then 5 days count against the new column name. But from the data set the dates are the same.
