### ISSUE TITLE
Trouble connecting to FlowViz (Project)

### ISSUE THREAD

**Issue by vladimir-jovanovic-1** [nbrown02/FlowViz#111] opened 2023-12-20 09:04 UTC
Hello,
I cannot seem to pass the server configuration screen. 
My ADO server's address is this: 
https://dev.azure.com/abc-ccll/klm%202.0

Can you assist me with connecting as I'm apparently doing something wrong?

![Screenshot 2023-12-20 at 10 02 05](https://github.com/nbrown02/FlowViz/assets/63601169/eeb01013-8054-47b1-a7e6-a0799926c33e)

The error I'm getting is below:

2 queries are blocked by the following errors:
WorkItems Completed
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems In Progress
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems In Progress2
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Dates
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Areas
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Iterations
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems Bl0cked
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems WIP Age
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems WIPLimit
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems FlowEfficiency
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItemTypes
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Teams
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Query parameters
Close

**Comment by nbrown02** [comment] 2023-12-20 09:13
Hi there,In the second field it should be analytics.dev.azure.com :) Sent from my iPhoneOn 20 Dec 2023, at 09:05, Vladimir Jovanović ***@***.***> wrote:﻿
Hello,
I cannot seem to pass the server configuration screen.
My ADO server's address is this:
https://dev.azure.com/abc-ccll/klm%202.0
Can you assist me with connecting as I'm apparently doing something wrong?
Screenshot.2023-12-20.at.10.02.05.png (view on web)
The error I'm getting is below:
2 queries are blocked by the following errors:
WorkItems Completed
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems In Progress
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems In Progress2
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Dates
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Areas
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Iterations
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems Bl0cked
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems WIP Age
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems WIPLimit
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItems FlowEfficiency
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
WorkItemTypes
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Teams
Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (The resource cannot be found.)
Query parameters
Close

**Comment by vladimir-jovanovic-1** [comment] 2023-12-20 09:39
Hi,
Thanks for the prompt response. 
I've checked the guide beforehand, but I don't have an analytics server. 
https://analytics.dev.azure.com/abc-ccll/klm%202.0 in the browser returns "Page not found." Should there be an analytics server in place in order to use FlowViz? 

Also, I thought it would be possible to connect as in the 2nd Example in the instructions: Example - connecting to Azure DevOps Server

**Comment by nbrown02** [comment] 2023-12-20 10:48
Ok - what is the Project URL of your Azure DevOps org? Anything dev.azure.com is Azure DevOps Services…ThanksSent from my iPhoneOn 20 Dec 2023, at 09:39, Vladimir Jovanović ***@***.***> wrote:﻿
Hi,
Thanks for the prompt response.
I've checked the guide beforehand, but I don't have an analytics server.
https://analytics.dev.azure.com/abc-ccll/klm%202.0 in the browser returns "Page not found." Should there be an analytics server in place in order to use FlowViz?
Also, I thought it would be possible to connect as in the 2nd Example in the instructions: Example - connecting to Azure DevOps Server

**Comment by vladimir-jovanovic-1** [comment] 2023-12-20 15:12
No PAT (token, I presume) in place, I'm going through an org login. 
Would you have an example of ADO? The only one I ever needed to use is the ADO Services. 
I will see to find out about it internally. 
Thanks.

**Comment by nbrown02** [comment] 2023-12-20 15:30
So my test ADO is https://dev.azure.com/nbtest/FlowVizWhere nbtest is the org name and FlowViz is the project name…It looks like from your message yours is the same?Sent from my iPhoneOn 20 Dec 2023, at 15:12, Vladimir Jovanović ***@***.***> wrote:﻿
No PAT (token, I presume) in place, I'm going through an org login.
Would you have an example of ADO? The only one I ever needed to use is the ADO Services.
I will see to find out about it internally.
Thanks.

**Comment by vladimir-jovanovic-1** [comment] 2023-12-20 15:37
Yes, mine is https://dev.azure.com/abc-ccll/klm%202.0. 
In this case: abc-ccl is org name, and klm 2.0 is the project name (it's represented funnily in the URL), inside ADO it is KLM 2.0.

**Comment by vladimir-jovanovic-1** [comment] 2023-12-20 20:53
It throws an error:
"{"error":{"code":"0","message":"VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account.","innererror":{"message":"VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account.","type":"Microsoft.VisualStudio.Services.Analytics.AnalyticsAccessCheckException","stacktrace":""}}}"

**Comment by nbrown02** [comment] 2023-12-20 21:20
So this is due to an access issue your end I’m afraid, it’s nothing to do with the template. My guess is you might have the wrong licence type (stakeholder) for analytics - your ADO admin will have to help you resolve it then the template should work…Sent from my iPhoneOn 20 Dec 2023, at 20:53, Vladimir Jovanović ***@***.***> wrote:﻿
It throws an error:
"{"error":{"code":"0","message":"VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account.","innererror":{"message":"VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account.","type":"Microsoft.VisualStudio.Services.Analytics.AnalyticsAccessCheckException","stacktrace":""}}}"

**Comment by vladimir-jovanovic-1** [comment] 2023-12-20 21:57
Thanks for the hint. 
I'll try and get support from admins.

**Comment by nbrown02** [comment] 2023-12-20 22:04
Once it’s sorted, remember it’s analytics.dev.azure.com for the second field then everything should load fine for you 👍🏼Sent from my iPhoneOn 20 Dec 2023, at 21:57, Vladimir Jovanović ***@***.***> wrote:﻿
Thanks for the hint.
I'll try and get support from admins.

**Comment by nbrown02** [comment] 2023-12-22 12:32
Closing as not a bug

**Closed by nbrown02** 2023-12-22 12:32 UTC
Labels: invalid, wontfix
