### ISSUE TITLE
Error : Access to the resource is forbidden

### ISSUE THREAD

**Issue by jenniferrosemitchell21** [nbrown02/FlowViz#119] opened 2024-02-15 10:00 UTC
Hi there Nick,
I'm trying to setup your FlowViz template for a new ADO Project but I get the below error. I've never had this error before, so coming to you for any suggestions please.
I am part of the Contributors group of the Project and I have also setup a PAT Code with 'Full Access', so I'm struggling to work out what else it could be.

![image](https://github.com/nbrown02/FlowViz/assets/134519976/a145bd3e-a633-43ef-82da-39916c97c8b4)

**Comment by nbrown02** [comment] 2024-02-15 10:03
If you try run a query in the URL browser, such as:

https://analytics.dev.azure.com/[ORG NAME]/[PROJECT NAME]/_odata/v3.0-preview/WorkItems?

What do you see? Normally the error message will indicate what the issue is around access...

**Comment by jenniferrosemitchell21** [comment] 2024-02-15 12:31
Oh great thanks - I totally forgot this test. So I do get an error ... makes sense ... which is about OData. Looking through ADO documentation I guess then that I am assigned as a 'Stakeholder'. I'll contact IT department. Thanks so much!


{
    "error": {
        "code": "0",
        "message": "VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account.",
        "innererror": {
            "message": "VS403527: Access to data from the Analytics OData endpoint is not available for all users. Either you have not been authenticated, or you do not have a paid license or subscription for this account.",
            "type": "Microsoft.VisualStudio.Services.Analytics.AnalyticsAccessCheckException",
            "stacktrace": ""
        }
    }
}

**Comment by nbrown02** [comment] 2024-02-15 13:12
Closing the issue :)

**Closed by nbrown02** 2024-02-15 13:12 UTC
Labels: invalid, wontfix
